server:
  port: 8080
spring:
  datasource:
    username: kenuo
    password: Kenuo@2018
    url: jdbc:mysql://rm-wz96ljp0mdpu7r359.mysql.rds.aliyuncs.com/cdcq?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver